---
# the fail2ban service won't start if any of the log files it's supposed to be
# watching are missing (eg in the ufw-port-scan section below)
- name: Ensure ufw logfile present before installing fail2ban
  copy:
    content: ""
    dest: /var/log/ufw.log
    force: no
    owner: syslog
    group: syslog
    mode: 0640

- name: install custom fail2ban filters
  template:
    src: "{{ item }}.j2"
    dest: "/etc/fail2ban/filter.d/{{ item }}"
  with_items:
    - ufw-port-scan.conf
    - repeat-offender.conf
  notify: restart fail2ban

- name: generate list of local server ips to add to whitelist
  shell: >
    ip addr | grep global | awk '/^ +inet / {split($2,a,"/"); print a[1]}' |  tr '\n' ' '
  register: dynamic_whitelist_ips
  changed_when: false

- name: install fail2ban jail config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: install script to show status of all fail2ban jails
  template:
    src: f2b-status-all.j2
    dest: /usr/local/bin/f2b-status-all
    mode: 0744

- name: Enable the fail2ban service
  systemd:
    name: fail2ban.service
    enabled: yes
    state: started
    daemon_reload: yes
