---
- name: Install sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify:
    - restart sshd

- name: manage SSH access from unknown origins
  ufw:
    comment: manage SSH access from unknown origins
    rule: "{{ 'deny' if knockd_enabled else 'allow' }}"
    port: "{{ sshd_port }}"
    proto: tcp
  notify: restart ufw
  tags: ufw

- name: Allow unlimited ssh access from whitelist_ips
  ufw:
    comment: allow unlimited ssh access from whitelist_ips
    rule: allow
    src: "{{ item }}"
    port: "{{ sshd_port }}"
    proto: tcp
    insert: 1 # to prevent lockouts it's important this rule is first
  with_items: "{{ whitelist_ips }}"
  notify: restart ufw
  tags: ufw

