---
- name: Install sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify:
    - restart sshd

- name: manage SSH access from unknown origins
  ufw:
    comment: manage SSH access from unknown origins
    rule: "{{ 'deny' if knockd_enabled else 'limit' }}"
    port: "{{ sshd_port }}"
    proto: tcp
  notify: restart ufw
  tags: ufw

- name: Allow unlimited ssh access from whitelist_ips
  ufw:
    comment: allow unlimited ssh access from whitelist_ips
    rule: allow
    src: "{{ item }}"
    port: "{{ sshd_port }}"
    proto: tcp
    insert: 1 # to prevent lockouts it's important this rule is first
  with_items: "{{ whitelist_ips }}"
  notify: restart ufw
  tags: ufw

- name: enable or disable knockd
  template:
    src: etc_default_knockd.j2
    dest: /etc/default/knockd
    mode: 0644
  notify:
    - restart or disable knockd

- name: Install knockd config
  template:
    src: knockd.conf.j2
    dest: /etc/knockd.conf
    mode: 0600
  notify:
    - restart or disable knockd
