---
- name: set timezone to UTC
  timezone:
    name: Etc/UTC

# https://blog.ubuntu.com/2016/01/20/data-driven-analysis-tmp-on-tmpfs
- name: Mount tmp on RAM based tmpfs
  tags: fstab
  mount:
    src: tmpfs
    name: /tmp
    fstype: tmpfs
    opts: rw,nosuid,nodev
    state: present

# https://askubuntu.com/a/440349
- name: reduce tendency to swap
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^vm.swappiness='
    line: vm.swappiness=1

- name: ensure that mlocate is executable
  file:
    path: "/etc/cron.daily/mlocate"
    state: file
    mode: "+x"
