---
- name: set timezone to UTC
  timezone:
    name: Etc/UTC

# https://blog.ubuntu.com/2016/01/20/data-driven-analysis-tmp-on-tmpfs
- name: Mount tmp on RAM based tmpfs
  tags: fstab
  mount:
    src: tmpfs
    name: /tmp
    fstype: tmpfs
    opts: rw,nosuid,nodev
    state: present

- name: add custom journald settings
  blockinfile:
    path: /etc/systemd/journald.conf
    block: |
      # make rate limiting less strict
      RateLimitInterval=30s
      RateLimitBurst=5000

      # https://www.freedesktop.org/software/systemd/man/journald.conf.html
      SystemMaxUse={{ systemd_journal_max_use }}
  notify: restart systemd-journald

# https://askubuntu.com/a/440349
- name: reduce tendency to swap
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^vm.swappiness='
    line: vm.swappiness=1

- name: ensure that mlocate is executable
  file:
    path: "/etc/cron.daily/mlocate"
    state: file
    mode: "+x"

- name: disable unneeded services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: "{{ systemd_services_to_disable }}"
  ignore_errors: yes

- name: ensure config file dest dirs exists
  file:
    path: "{{ item.dest_fullpath | dirname }}"
    state: directory
  with_items: "{{ config_files_to_install_via_file }}"

- name: copy misc config files from playbook_dir
  copy:
    src: "{{ playbook_dir }}/files/config_files/{{ item.filename }}"
    dest: "{{ item.dest_fullpath }}"
    mode: 0644
  with_items: "{{ config_files_to_install_via_file }}"

- name: set up logrotation for log from remote_logger plugin
  template:
    src: remote-logger-logrotation.j2
    dest: "/etc/logrotate.d/ansible-remote-logger"
    mode: 0644
