---
- name: restart ufw
  systemd:
    name: ufw
    enabled: yes
    state: restarted

- name: restart sshd
  systemd:
    name: sshd
    enabled: yes
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    state: restarted

- name: restart or disable knockd
  systemd:
    name: knockd
    enabled: "{{ knockd_enabled }}"
    state: "{{ 'restarted' if knockd_enabled else 'stopped' }}"

- name: restart rsyslog
  systemd:
    name: rsyslog
    enabled: yes
    state: restarted

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    enabled: yes
    state: restarted
    daemon_reload: yes
